#!/usr/bin/env python3
"""randchoice

Read lines from stdin or choose from arguments passed to script and print a
choice from one of those options.
"""

import sys
import logging
import random
import termcolor

logging.basicConfig(level=logging.WARNING)


def main():
    if len(sys.argv) == 1:
        options = []
        for line in sys.stdin:
            options.append(line.strip())
    else:
        options = sys.argv[1:]

    logging.debug(options)

    random.seed()
    selection = random.choice(options)

    if sys.stdout.isatty():
        styled_selection = termcolor.colored(
            f' {selection} ',
            attrs=['bold', 'reverse']
        )
        print(
            '\n'
            f'The choice is {styled_selection}'
            '\n'
        )
    else:
        print(selection)

    return 0


if __name__ == '__main__':
    sys.exit(main())
