#!/usr/bin/env python3
"""randchoice

Read lines from stdin or choose from arguments passed to script and print a
choice from one of those options.
"""

import sys
import logging
import random
from blessings import Terminal

logging.basicConfig(level=logging.WARNING)


def main():
    if len(sys.argv) == 1:
        options = []
        for line in sys.stdin:
            options.append(line.strip())
    else:
        options = sys.argv[1:]

    logging.debug(options)

    random.seed()
    selection = random.choice(options)

    if sys.stdout.isatty():
        term = Terminal()
        print(
            'The choice is ' +
            term.reverse(term.bold(f' {selection} '))
        )
    else:
        print(selection)

    return 0


if __name__ == '__main__':
    sys.exit(main())
